# Generated by Django 4.1.7 on 2023-03-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название книги')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание книги')),
                ('count_pages', models.IntegerField(null=True, verbose_name='Количество страниц')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('cover_type', models.CharField(max_length=50, null=True, verbose_name='Тип обложки')),
                ('size', models.CharField(max_length=50, null=True, verbose_name='Размер книги')),
                ('publication_date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
        ),
    ]
